-- Seed the institutionally supplied operational-code catalog without
-- modifying historical migrations or overwriting locally customized records.
INSERT INTO "OperationalCode" ("id", "code", "description", "category", "sortOrder", "createdAt", "updatedAt")
VALUES
('operational_f_1','F-1','Incendio Residencial','Emergencia',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_2','F-2','Incendio en Comercio o Industria','Emergencia',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_3','F-3','Escape de Gas (GLP/GNL)','Emergencia',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_4','F-4','Incendio/Incidente Eléctrico','Emergencia',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_5','F-5','Incendio en Vehículo de Motor','Emergencia',5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_6','F-6','Incendio Forestal, Basura, Gomas','Emergencia',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_7','F-7','Incidente con Materiales Peligrosos','Emergencia',7,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_8','F-8','Derrame/Incidente de Fluidos en vía pública','Emergencia',8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_9','F-9','Incendio en Embarcación','Emergencia',9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_f_10','F-10','Incendio en Aeronave','Emergencia',10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_e_1','E-1','Explosión','Emergencia',11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_d_2','D-2','Deslizamiento/Derrumbe/Colapso','Emergencia',12,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_i_1','I-1','Inundación','Emergencia',13,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_poda','PODA','Corte de Árbol','Otros',14,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_md','MD','Servicio de Ambulancia','Otros',15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_ho','H.O','Agua','Otros',16,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_ps','PS','Prevención Siniestro','Otros',17,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_pm','PM','Prevención Médica','Otros',18,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_fao','FAO','Falsa Alarma Ocurrida','Otros',19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r_1','R-1','Rescate Acuático','Emergencia',20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r_2','R-2','Rescate Terrestre','Emergencia',21,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r_3','R-3','Rescate en Altura','Emergencia',22,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r_4','R-4','Rescate Animales (Peligrosos o No)','Emergencia',23,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r_5','R-5','Rescate Vehicular (Extracción Vehicular)','Emergencia',24,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_15','1-15','Accidente Personal','Emergencia',25,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_16','1-16','Accidente de Tránsito Terrestre','Emergencia',26,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_17','1-17','Accidente Aéreo (Aeronave Caída)','Emergencia',27,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_26','1-26','Persona visiblemente ilesa','Condición',28,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_27','1-27','Persona afectada/lesionada leve (visiblemente no peligra la vida)','Condición',29,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_28','1-28','Persona inconsciente/con fractura/con herida penetrante (puede peligrar la vida)','Condición',30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_1_29','1-29','Persona fallecida','Condición',31,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_r','R','Repetir mensaje','Otros',32,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_500','500','Hacer contacto vía telefónica','Otros',33,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_k_1','K-1','Desperfecto Mecánico','Otros',34,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_pn','PN','Policía Nacional','Institución',35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_digesett','DIGESETT','Dirección General de Seguridad de Tránsito y Transporte Terrestre','Institución',36,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_cde','CDE','Compañías Eléctricas (EDEESTE/EDESUR/EDENORTE)','Institución',37,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('operational_coe','COE','Centro de Operaciones de Emergencias','Institución',38,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO NOTHING;
