import { requirePagePermission } from "@/modules/auth/permissions/page-authorization"; import { ContentPanel } from "@/components/ui/content-panel"; import { ModuleHeader } from "@/components/ui/module-header";
import { createPositionAction } from "@/modules/institutional-catalog/catalog.actions"; import { listDepartments, listPositions } from "@/modules/institutional-catalog/catalog.service";
import { CatalogCreateForm } from "@/modules/institutional-catalog/components/catalog-create-form"; import { CatalogTable } from "@/modules/institutional-catalog/components/catalog-table";

export default async function PositionsPage() {
  const context = await requirePagePermission("catalogo.view"); const [items, departments] = await Promise.all([listPositions(), listDepartments()]);
  const departmentOptions = departments.filter((item) => item.isActive).map((item) => ({ value: item.id, label: item.name }));
  const fields = [{ name: "name", label: "Nombre", required: true, maxLength: 120, placeholder: "Nombre del cargo" }, { name: "departmentId", label: "Departamento", options: departmentOptions }, { name: "description", label: "Descripción", maxLength: 250, placeholder: "Descripción opcional" }, { name: "sortOrder", label: "Orden", type: "number" as const, required: true }] as const;
  return <div className="space-y-7"><ModuleHeader eyebrow="Catálogo institucional" title="Cargos" action={context.permissions.has("catalogo.manage") ? <CatalogCreateForm action={createPositionAction} fields={fields} buttonLabel="Nuevo cargo" title="Nuevo cargo" submitLabel="Crear cargo" /> : undefined} description="Funciones institucionales asociadas, cuando corresponde, a un departamento." stats={[{ label: "Total", value: items.length }, { label: "Activos", value: items.filter((item) => item.isActive).length }]} /><ContentPanel title="Cargos registrados"><CatalogTable entity="position" canManage={context.permissions.has("catalogo.manage")} items={items} emptyMessage="No hay cargos registrados." editFields={(item) => fields.map((field) => ({ ...field, value: field.name === "departmentId" ? item.departmentId : item[field.name as "name" | "description" | "sortOrder"] }))} columns={[{ label: "Cargo", render: (item) => <span className="font-semibold text-slate-950 dark:text-white">{item.name}</span> }, { label: "Departamento", render: (item) => item.department?.name ?? "Sin departamento" }, { label: "Descripción", render: (item) => item.description ?? "—" }]} /></ContentPanel></div>;
}