import { ContentPanel } from "@/components/ui/content-panel";
import { ModuleHeader } from "@/components/ui/module-header";
import { updateInstitutionalSettingsAction } from "@/modules/institutional-catalog/settings.actions";
import { getInstitutionalSettings } from "@/modules/institutional-catalog/settings.service";

type Props = { searchParams: Promise<{ saved?: string; error?: string }> };
const inputClass = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 outline-none transition focus:border-red-400 focus:ring-4 focus:ring-red-100 dark:border-slate-700 dark:bg-slate-950 dark:text-white dark:focus:border-red-700 dark:focus:ring-red-950/40";

export default async function InstitutionalSettingsPage({ searchParams }: Props) {
  const [settings, params] = await Promise.all([getInstitutionalSettings(), searchParams]);
  return <div className="space-y-7"><ModuleHeader eyebrow="Administración" title="Configuración institucional" description="Información general de la institución utilizada por SIBOR." />{params.saved ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-300">Configuración guardada correctamente.</div> : null}{params.error ? <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-800 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">{params.error}</div> : null}<form action={updateInstitutionalSettingsAction}><ContentPanel title="Datos institucionales" description="Estos datos son administrativos; los secretos y credenciales nunca se almacenan aquí."><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">{[["organizationName","Nombre institucional",settings?.organizationName ?? "Cuerpo de Bomberos de La Romana"],["shortName","Nombre corto",settings?.shortName ?? "SIBOR"],["address","Dirección",settings?.address ?? ""],["phone","Teléfono",settings?.phone ?? ""],["email","Correo institucional",settings?.email ?? ""]].map(([name,label,value]) => <div key={name}><label htmlFor={name} className="text-sm font-semibold text-slate-700 dark:text-slate-200">{label}</label><input id={name} name={name} defaultValue={value} required={name === "organizationName" || name === "shortName"} className={inputClass} /></div>)}</div><div className="flex justify-end border-t border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><button type="submit" className="rounded-xl bg-red-700 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-red-800">Guardar configuración</button></div></ContentPanel></form></div>;
}
