import { requirePagePermission } from "@/modules/auth/permissions/page-authorization";
import { ContentPanel } from "@/components/ui/content-panel"; import { ModuleHeader } from "@/components/ui/module-header";
import { createDepartmentAction } from "@/modules/institutional-catalog/catalog.actions"; import { listDepartments } from "@/modules/institutional-catalog/catalog.service";
import { CatalogCreateForm } from "@/modules/institutional-catalog/components/catalog-create-form"; import { CatalogTable } from "@/modules/institutional-catalog/components/catalog-table";

export default async function DepartmentsPage() {
  const context = await requirePagePermission("catalogo.view"); const items = await listDepartments();
  const parentOptions = items.filter((item) => item.isActive).map((item) => ({ value: item.id, label: item.name }));
  const fields = [{ name: "name", label: "Nombre", required: true, maxLength: 120, placeholder: "Nombre del departamento" }, { name: "parentId", label: "Depende de", options: parentOptions }, { name: "description", label: "Descripción", maxLength: 250, placeholder: "Descripción opcional" }, { name: "sortOrder", label: "Orden", type: "number" as const, required: true }] as const;
  return <div className="space-y-7"><ModuleHeader eyebrow="Catálogo institucional" title="Departamentos" description="Estructura organizacional que posteriormente utilizará el expediente de Personal." stats={[{ label: "Total", value: items.length }, { label: "Activos", value: items.filter((item) => item.isActive).length }]} /><ContentPanel title="Nuevo departamento"><CatalogCreateForm action={createDepartmentAction} fields={fields} /></ContentPanel><ContentPanel title="Departamentos registrados"><CatalogTable entity="department" canManage={context.permissions.has("catalogo.manage")} items={items} emptyMessage="No hay departamentos registrados." editFields={(item) => fields.map((field) => ({ ...field, options: field.name === "parentId" ? parentOptions.filter((option) => option.value !== item.id) : "options" in field ? field.options : undefined, value: field.name === "parentId" ? item.parentId : item[field.name as "name" | "description" | "sortOrder"] }))} columns={[{ label: "Departamento", render: (item) => <span className="font-semibold text-slate-950 dark:text-white">{item.name}</span> }, { label: "Depende de", render: (item) => item.parent?.name ?? "—" }, { label: "Cargos", render: (item) => item._count.positions }, { label: "Subáreas", render: (item) => item._count.children }]} /></ContentPanel></div>;
}